# Copyright (c) 2024 Renan Evaristo

HTTP_OK = 200
HTTP_TOO_MANY_REQUESTS = 429
TOP_FOUR = 4
DEBUG = True

CLASS_MAPPER = {
    # Nomes da API da Riot : Nome Bonito no Jogo
    "ASTrait": "Challenger",
    "HPTank": "Brawler",
    "ResistTank": "Bastion",
    "ShieldTank": "Vanguard",
    "ManaTrait": "Conduit",
    "MeleeTrait": "Marauder",
    "RangedTrait": "Sniper",
    "AssassinTrait": "Rogue",
    "APTrait": "Replicator",
    "SummonTrait": "Shepherd",
    "FlexTrait": "Voyager",
    "Fateweaver": "Fateweaver",
}
CHAMPION_TRAITS = {
    "Aatrox": ["Challenger", "Brawler"],
    "Briar": ["Rogue", "Brawler"],
    "Caitlyn": ["Sniper", "AnimaSquad"],
    "Chogath": ["Brawler", "Primordian"],
    "Ezreal": ["Sniper", "PsyOps"],
    "Leona": ["Bastion", "Vanguard"],
    "Lissandra": ["Replicator", "DarkStar"],
    "Nasus": ["Brawler", "Bastion"],
    "Poppy": ["Vanguard", "SpaceGroove"],
    "RekSai": ["Marauder", "Rogue"],
    "Talon": ["Rogue", "PsyOps"],
    "Teemo": ["Replicator", "SpaceGroove"],
    "TwistedFate": ["Conduit", "Fateweaver"],
    "Veigar": ["Replicator", "Astronaut"],
    "Akali": ["Rogue", "DRX"],
    "Belveth": ["Marauder", "DarkStar"],
    "Gnar": ["Brawler", "Marauder"],
    "Gragas": ["Bastion", "SpaceGroove"],
    "Gwen": ["Replicator", "AnimaSquad"],
    "Jax": ["Vanguard", "Mecha"],
    "Jinx": ["Sniper", "AnimaSquad"],
    "Meepsie": ["Shepherd", "SpaceGroove"],
    "Milio": ["Replicator", "SpaceGroove"],
    "Mordekaiser": ["Vanguard", "DarkStar"],
    "Pantheon": ["Bastion", "DRX"],
    "Pyke": ["Rogue", "PsyOps"],
    "Zoe": ["Replicator", "Fateweaver"],
    "Aurora": ["Conduit", "Astronaut"],
    "Diana": ["Replicator", "DarkStar"],
    "Fizz": ["Rogue", "SpaceGroove"],
    "Illaoi": ["Brawler", "DRX"],
    "Kaisa": ["Sniper", "AnimaSquad"],
    "Lulu": ["Conduit", "SpaceGroove"],
    "Maokai": ["Brawler", "Astronaut"],
    "MissFortune": ["Sniper", "AnimaSquad"],
    "Ornn": ["Bastion", "Astronaut"],
    "Rhaast": ["Marauder", "Primordian"],
    "Samira": ["Sniper", "PsyOps"],
    "Urgot": ["Sniper", "Primordian"],
    "Viktor": ["Replicator", "PsyOps"],
    "AurelionSol": ["Conduit", "DarkStar"],
    "Corki": ["Sniper", "Astronaut"],
    "Karma": ["Replicator", "DarkStar"],
    "Kindred": ["Sniper", "Fateweaver"],
    "Leblanc": ["Replicator", "DarkStar"],
    "MasterYi": ["Marauder", "PsyOps"],
    "Nami": ["Conduit", "SpaceGroove"],
    "Nunu": ["Brawler", "SpaceGroove"],
    "Rammus": ["Bastion", "SpaceGroove"],
    "Riven": ["Vanguard", "AnimaSquad"],
    "TahmKench": ["Brawler", "SpaceGroove"],
    "TheMightyMech": ["Mecha", "Brawler"],
    "Xayah": ["Sniper", "DRX"],
    "Bard": ["Conduit", "Astronaut"],
    "Blitzcrank": ["Vanguard", "SpaceGroove"],
    "Fiora": ["Marauder", "AnimaSquad"],
    "Graves": ["Sniper", "DRX"],
    "Jhin": ["Sniper", "DarkStar"],
    "Morgana": ["Replicator", "DarkStar"],
    "Shen": ["Bastion", "DRX"],
    "Sona": ["Conduit", "SpaceGroove"],
    "Vex": ["Replicator", "DarkStar"],
    "Zed": ["Rogue", "PsyOps"],
}

UNITS_NAME = {
    "Aatrox",
    "Briar",
    "Caitlyn",
    "Chogath",
    "Ezreal",
    "Leona",
    "Lissandra",
    "Nasus",
    "Poppy",
    "RekSai",
    "Talon",
    "Teemo",
    "Twisted Fate",
    "Veigar",
    "Akali",
    "Belveth",
    "Gnar",
    "Gragas",
    "Gwen",
    "Jax",
    "Jinx",
    "Meepsie",
    "Milio",
    "Mordekaiser",
    "Pantheon",
    "Pyke",
    "Zoe",
    "Aurora",
    "Diana",
    "Fizz",
    "Illaoi",
    "Kaisa",
    "Lulu",
    "Maokai",
    "Miss Fortune",
    "Ornn",
    "Rhaast",
    "Samira",
    "Urgot",
    "Viktor",
    "Aurelion Sol",
    "Corki",
    "Karma",
    "Kindred",
    "Leblanc",
    "Master Yi",
    "Nami",
    "Nunu",
    "Rammus",
    "Riven",
    "Tahm Kench",
    "The Mighty Mech",
    "Xayah",
    "Bard",
    "Blitzcrank",
    "Fiora",
    "Graves",
    "Jhin",
    "Morgana",
    "Shen",
    "Sona",
    "Vex",
    "Zed",
}
